### ISSUE TITLE
При первом запуске программы падает стэктрейс что файл не найден 

### ISSUE THREAD

**Issue by ghost** [vadym685/NCTaskManagerMVC#3]
При первом запуске программы падает стэктрейс что файл не найден 

`java.io.FileNotFoundException: \NCTaskManagerMVC-lab1\NCTaskManagerMVC-lab1\data.json (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at ua.edu.sumdu.j2se.kushnir.tasks.model.TaskIO.readText(TaskIO.java:128)
	at ua.edu.sumdu.j2se.kushnir.tasks.Application.loadTaskData(Application.java:45)
	at ua.edu.sumdu.j2se.kushnir.tasks.Application.start(Application.java:32)
	at ua.edu.sumdu.j2se.kushnir.tasks.Main.main(Main.java:7)`

Добавь функциональность создания файла для хранения задач если его нету.

**Comment by vadym685** [comment]
https://github.com/vadym685/NCTaskManagerMVC/commit/80ec60358d629e390bbaebfeb6545bfa9fb602e8
